### PR TITLE
DM-37545: Modernize coding standards

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Review by ktlim — APPROVED** [review]
It looks like `configurator.py` is not used now.  You did remove the test for it.
It also looks like there are still `orca` references in `etc/templates` (and `.gitignore`).
But after fixing thosse it looks OK to merge.

**Comment by ktlim** [comment]
Would be good to get a README from @daues.

**Comment by timj** [comment]
I'm not really sure what I'm supposed to do with the etc/templates files that contain orca references. Do I delete the entire file or just remove the lines that mention orca?

**Comment by daues** [comment]
I believe the Glide-ins are not making use of ctrl_execute/etc at all;  perhaps the whole directory can be removed. 
 I could do more purge & test to see what can be just removed.

**Comment by timj** [comment]
@daues okay, for now I will remove the three that use orca and then merge this so you can continue your work.

**Pull request merged**
